package main

import (
	"os"
	"path/filepath"
	"testing"
)

const staleFixture = `// Code generated by defc; DO NOT EDIT.

package test

func __IfaceMergeNamedArgs(argsMap map[string]any) map[string]any {
	return argsMap
}
`

const freshFixture = `// Code generated by defc; DO NOT EDIT.

package test

func __IfaceMergeNamedArgs(argsMap map[string]any) (map[string]any, error) {
	return argsMap, nil
}
`

const unrelatedFixture = `package test

func Hello() string { return "world" }
`

func TestDoctor_IsStaleGeneratedFile(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "stale.go")
	fresh := filepath.Join(dir, "fresh.go")
	other := filepath.Join(dir, "other.go")
	for _, p := range [][2]string{
		{stale, staleFixture},
		{fresh, freshFixture},
		{other, unrelatedFixture},
	} {
		if err := os.WriteFile(p[0], []byte(p[1]), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	s, err := isStaleGeneratedFile(stale)
	if err != nil {
		t.Fatalf("stale: %v", err)
	}
	if !s {
		t.Fatalf("stale file not flagged")
	}
	if s, err := isStaleGeneratedFile(fresh); err != nil || s {
		t.Fatalf("fresh file flagged: s=%v err=%v", s, err)
	}
	if s, err := isStaleGeneratedFile(other); err != nil || s {
		t.Fatalf("non-generated file flagged: s=%v err=%v", s, err)
	}
}
