package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

var (
	doctorProject    string
	doctorFailStale  bool
	doctorGenMarker  = "Code generated by defc"
	doctorLegacySig  = regexp.MustCompile(
		`func __[A-Za-z_][A-Za-z0-9_]*MergeNamedArgs\(argsMap map\[string\]any\)\s+map\[string\]any\s*\{`)
)

var doctorCmd = &cobra.Command{
	Use:   "doctor",
	Short: "Diagnose stale defc-generated files",
	Long: `doctor walks a project directory and reports Go files generated by
older versions of defc whose inlined __<Ident>MergeNamedArgs function
lacks the v1.45.0 duplicate-bind-key collision detection.

Exit codes:
  0   no stale files (or --fail-on-stale not set)
  1   stale files found and --fail-on-stale set
  64  usage / IO error`,
	SilenceUsage:  true,
	SilenceErrors: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		root := doctorProject
		if root == "" {
			root = "."
		}
		info, err := os.Stat(root)
		if err != nil {
			return usageErr(fmt.Errorf("doctor: %w", err))
		}
		if !info.IsDir() {
			return usageErr(fmt.Errorf("doctor: --project %q must be a directory", root))
		}
		stale := make([]string, 0)
		walkErr := filepath.WalkDir(root, func(path string, d fs.DirEntry, werr error) error {
			if werr != nil {
				return werr
			}
			if d.IsDir() {
				name := d.Name()
				if name == ".git" || name == "node_modules" || name == "vendor" {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") {
				return nil
			}
			isStale, serr := isStaleGeneratedFile(path)
			if serr != nil {
				return fmt.Errorf("%s: %w", path, serr)
			}
			if isStale {
				stale = append(stale, path)
				fmt.Fprintf(cmd.OutOrStdout(),
					"%s: generated with defc <v1.45.0 — MergeNamedArgs collision detection disabled; regenerate with defc >= v1.45.0\n",
					path)
			}
			return nil
		})
		if walkErr != nil {
			return usageErr(walkErr)
		}
		if doctorFailStale && len(stale) > 0 {
			os.Exit(1)
		}
		return nil
	},
}

func isStaleGeneratedFile(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 16*1024*1024)

	var sawMarker bool
	var sawLegacyMerge bool
	var sawStrictMerge bool
	for scanner.Scan() {
		line := scanner.Text()
		if !sawMarker && strings.Contains(line, doctorGenMarker) {
			sawMarker = true
		}
		if doctorLegacySig.MatchString(line) {
			sawLegacyMerge = true
		}
		// Strict form ends with `(map[string]any, error) {`
		if strings.Contains(line, "MergeNamedArgs(argsMap map[string]any)") &&
			strings.Contains(line, "(map[string]any, error)") {
			sawStrictMerge = true
		}
	}
	if err := scanner.Err(); err != nil {
		return false, err
	}
	if !sawMarker {
		return false, nil
	}
	if sawStrictMerge {
		return false, nil
	}
	return sawLegacyMerge, nil
}

func init() {
	defc.AddCommand(doctorCmd)
	f := doctorCmd.Flags()
	f.StringVar(&doctorProject, "project", "", "project directory to scan (default current directory)")
	f.BoolVar(&doctorFailStale, "fail-on-stale", false, "exit 1 if any stale files are found (for CI)")
}
